const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");

export function bidRequestEmail(data: { recipientName: string; companyName: string; companyLogo?: string; number: number; projectName: string; deadline: Date; responseLink: string; message?: string }) {
  const logo = data.companyLogo
    ? `<img src="${escapeHtml(data.companyLogo)}" alt="${escapeHtml(data.companyName)}" style="display:block;max-width:150px;max-height:54px;object-fit:contain">`
    : `<div style="font-size:20px;font-weight:700;color:#101827">${escapeHtml(data.companyName)}</div>`;
  const deadline = data.deadline.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
  const customMessage = data.message ? `<div style="margin:22px 0;padding:16px;background:#faf8f4;border-left:3px solid #b99155;color:#4b5563;line-height:1.6">${escapeHtml(data.message)}</div>` : "";
  return `<!doctype html><html><body style="margin:0;background:#f4f5f7;font-family:Arial,sans-serif;color:#101827"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="600" style="max-width:600px;width:100%;background:#fff;border:1px solid #e5e7eb"><tr><td style="padding:28px 32px;border-bottom:3px solid #b99155">${logo}</td></tr><tr><td style="padding:34px 32px"><div style="font-size:11px;letter-spacing:2px;color:#b07d36;font-weight:700">BID REQUEST #${data.number}</div><h1 style="margin:10px 0 18px;font-size:26px">A project is ready for your bid</h1><p style="color:#4b5563;line-height:1.6">Hello ${escapeHtml(data.recipientName)}, ${escapeHtml(data.companyName)} invited you to submit a proposal for <strong>${escapeHtml(data.projectName)}</strong>.</p>${customMessage}<p style="color:#4b5563">Response deadline: <strong>${deadline}</strong></p><table role="presentation" style="margin:26px 0"><tr><td style="background:#101827;border-radius:5px"><a href="${escapeHtml(data.responseLink)}" style="display:inline-block;padding:13px 22px;color:#fff;text-decoration:none;font-weight:700">View &amp; Submit Bid</a></td></tr></table><p style="font-size:12px;color:#6b7280;line-height:1.6">This secure link is unique to your company. Do not forward it.</p></td></tr></table></td></tr></table></body></html>`;
}
